#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.225
=======
//     Runtime Version:4.0.30319.235
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



<<<<<<< HEAD
[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBvrijstellingen")]
=======
[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
public partial class VrijstellingenDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
<<<<<<< HEAD
  partial void InserttblAdmin(tblAdmin instance);
  partial void UpdatetblAdmin(tblAdmin instance);
  partial void DeletetblAdmin(tblAdmin instance);
  partial void InserttblKoppel(tblKoppel instance);
  partial void UpdatetblKoppel(tblKoppel instance);
  partial void DeletetblKoppel(tblKoppel instance);
  partial void InserttblLeerkracht(tblLeerkracht instance);
  partial void UpdatetblLeerkracht(tblLeerkracht instance);
  partial void DeletetblLeerkracht(tblLeerkracht instance);
  partial void InserttblRapport(tblRapport instance);
  partial void UpdatetblRapport(tblRapport instance);
  partial void DeletetblRapport(tblRapport instance);
  partial void InserttblStudent(tblStudent instance);
  partial void UpdatetblStudent(tblStudent instance);
  partial void DeletetblStudent(tblStudent instance);
  partial void InserttblVakken(tblVakken instance);
  partial void UpdatetblVakken(tblVakken instance);
  partial void DeletetblVakken(tblVakken instance);
  partial void InserttblVrijstelling(tblVrijstelling instance);
  partial void UpdatetblVrijstelling(tblVrijstelling instance);
  partial void DeletetblVrijstelling(tblVrijstelling instance);
  #endregion
	
	public VrijstellingenDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBvrijstellingenConnectionString"].ConnectionString, mappingSource)
=======
  partial void InsertOpleiding(Opleiding instance);
  partial void UpdateOpleiding(Opleiding instance);
  partial void DeleteOpleiding(Opleiding instance);
  partial void InsertVrijstelling(Vrijstelling instance);
  partial void UpdateVrijstelling(Vrijstelling instance);
  partial void DeleteVrijstelling(Vrijstelling instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  partial void InsertUpload(Upload instance);
  partial void UpdateUpload(Upload instance);
  partial void DeleteUpload(Upload instance);
  partial void InsertVakken(Vakken instance);
  partial void UpdateVakken(Vakken instance);
  partial void DeleteVakken(Vakken instance);
  #endregion
	
	public VrijstellingenDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	{
		OnCreated();
	}
	
	public VrijstellingenDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VrijstellingenDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VrijstellingenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VrijstellingenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
<<<<<<< HEAD
	public System.Data.Linq.Table<tblAdmin> tblAdmins
	{
		get
		{
			return this.GetTable<tblAdmin>();
		}
	}
	
	public System.Data.Linq.Table<tblKoppel> tblKoppels
	{
		get
		{
			return this.GetTable<tblKoppel>();
		}
	}
	
	public System.Data.Linq.Table<tblLeerkracht> tblLeerkrachts
	{
		get
		{
			return this.GetTable<tblLeerkracht>();
		}
	}
	
	public System.Data.Linq.Table<tblRapport> tblRapports
	{
		get
		{
			return this.GetTable<tblRapport>();
		}
	}
	
	public System.Data.Linq.Table<tblStudent> tblStudents
	{
		get
		{
			return this.GetTable<tblStudent>();
		}
	}
	
	public System.Data.Linq.Table<tblVakken> tblVakkens
	{
		get
		{
			return this.GetTable<tblVakken>();
		}
	}
	
	public System.Data.Linq.Table<tblVrijstelling> tblVrijstellings
	{
		get
		{
			return this.GetTable<tblVrijstelling>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAdmin")]
public partial class tblAdmin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_adminID;
	
	private double _adminStatus;
	
	private double _adminBijlage;
	
	private double _adminGoedgekeurd;
	
	private string _fk_caseID;
	
	private EntitySet<tblKoppel> _tblKoppels;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_adminIDChanging(int value);
    partial void Onpk_adminIDChanged();
    partial void OnadminStatusChanging(double value);
    partial void OnadminStatusChanged();
    partial void OnadminBijlageChanging(double value);
    partial void OnadminBijlageChanged();
    partial void OnadminGoedgekeurdChanging(double value);
    partial void OnadminGoedgekeurdChanged();
    partial void Onfk_caseIDChanging(string value);
    partial void Onfk_caseIDChanged();
    #endregion
	
	public tblAdmin()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_adminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_adminID
	{
		get
		{
			return this._pk_adminID;
		}
		set
		{
			if ((this._pk_adminID != value))
			{
				this.Onpk_adminIDChanging(value);
				this.SendPropertyChanging();
				this._pk_adminID = value;
				this.SendPropertyChanged("pk_adminID");
				this.Onpk_adminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminStatus", DbType="Float NOT NULL")]
	public double adminStatus
	{
		get
		{
			return this._adminStatus;
		}
		set
		{
			if ((this._adminStatus != value))
			{
				this.OnadminStatusChanging(value);
				this.SendPropertyChanging();
				this._adminStatus = value;
				this.SendPropertyChanged("adminStatus");
				this.OnadminStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminBijlage", DbType="Float NOT NULL")]
	public double adminBijlage
	{
		get
		{
			return this._adminBijlage;
		}
		set
		{
			if ((this._adminBijlage != value))
			{
				this.OnadminBijlageChanging(value);
				this.SendPropertyChanging();
				this._adminBijlage = value;
				this.SendPropertyChanged("adminBijlage");
				this.OnadminBijlageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminGoedgekeurd", DbType="Float NOT NULL")]
	public double adminGoedgekeurd
	{
		get
		{
			return this._adminGoedgekeurd;
		}
		set
		{
			if ((this._adminGoedgekeurd != value))
			{
				this.OnadminGoedgekeurdChanging(value);
				this.SendPropertyChanging();
				this._adminGoedgekeurd = value;
				this.SendPropertyChanged("adminGoedgekeurd");
				this.OnadminGoedgekeurdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_caseID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string fk_caseID
	{
		get
		{
			return this._fk_caseID;
		}
		set
		{
			if ((this._fk_caseID != value))
			{
				this.Onfk_caseIDChanging(value);
				this.SendPropertyChanging();
				this._fk_caseID = value;
				this.SendPropertyChanged("fk_caseID");
				this.Onfk_caseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAdmin_tblKoppel", Storage="_tblKoppels", ThisKey="pk_adminID", OtherKey="fk_adminID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblAdmin = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblAdmin = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKoppel")]
public partial class tblKoppel : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pk_caseID;
	
	private int _fk_leerlingID;
	
	private int _fk_vrijstellingID;
	
	private int _fk_leerkrachtID;
	
	private int _fk_adminID;
	
	private int _fk_vakkenID;
	
	private int _fk_rapportID;
	
	private EntityRef<tblAdmin> _tblAdmin;
	
	private EntityRef<tblLeerkracht> _tblLeerkracht;
	
	private EntityRef<tblRapport> _tblRapport;
	
	private EntityRef<tblStudent> _tblStudent;
	
	private EntityRef<tblVakken> _tblVakken;
	
	private EntityRef<tblVrijstelling> _tblVrijstelling;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_caseIDChanging(int value);
    partial void Onpk_caseIDChanged();
    partial void Onfk_leerlingIDChanging(int value);
    partial void Onfk_leerlingIDChanged();
    partial void Onfk_vrijstellingIDChanging(int value);
    partial void Onfk_vrijstellingIDChanged();
    partial void Onfk_leerkrachtIDChanging(int value);
    partial void Onfk_leerkrachtIDChanged();
    partial void Onfk_adminIDChanging(int value);
    partial void Onfk_adminIDChanged();
    partial void Onfk_vakkenIDChanging(int value);
    partial void Onfk_vakkenIDChanged();
    partial void Onfk_rapportIDChanging(int value);
    partial void Onfk_rapportIDChanged();
    #endregion
	
	public tblKoppel()
	{
		this._tblAdmin = default(EntityRef<tblAdmin>);
		this._tblLeerkracht = default(EntityRef<tblLeerkracht>);
		this._tblRapport = default(EntityRef<tblRapport>);
		this._tblStudent = default(EntityRef<tblStudent>);
		this._tblVakken = default(EntityRef<tblVakken>);
		this._tblVrijstelling = default(EntityRef<tblVrijstelling>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_caseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_caseID
	{
		get
		{
			return this._pk_caseID;
		}
		set
		{
			if ((this._pk_caseID != value))
			{
				this.Onpk_caseIDChanging(value);
				this.SendPropertyChanging();
				this._pk_caseID = value;
				this.SendPropertyChanged("pk_caseID");
				this.Onpk_caseIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_leerlingID", DbType="Int NOT NULL")]
	public int fk_leerlingID
	{
		get
		{
			return this._fk_leerlingID;
		}
		set
		{
			if ((this._fk_leerlingID != value))
			{
				if (this._tblStudent.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_leerlingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_leerlingID = value;
				this.SendPropertyChanged("fk_leerlingID");
				this.Onfk_leerlingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vrijstellingID", DbType="Int NOT NULL")]
	public int fk_vrijstellingID
	{
		get
		{
			return this._fk_vrijstellingID;
		}
		set
		{
			if ((this._fk_vrijstellingID != value))
			{
				if (this._tblVrijstelling.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vrijstellingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vrijstellingID = value;
				this.SendPropertyChanged("fk_vrijstellingID");
				this.Onfk_vrijstellingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_leerkrachtID", DbType="Int NOT NULL")]
	public int fk_leerkrachtID
	{
		get
		{
			return this._fk_leerkrachtID;
		}
		set
		{
			if ((this._fk_leerkrachtID != value))
			{
				if (this._tblLeerkracht.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_leerkrachtIDChanging(value);
				this.SendPropertyChanging();
				this._fk_leerkrachtID = value;
				this.SendPropertyChanged("fk_leerkrachtID");
				this.Onfk_leerkrachtIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_adminID", DbType="Int NOT NULL")]
	public int fk_adminID
	{
		get
		{
			return this._fk_adminID;
		}
		set
		{
			if ((this._fk_adminID != value))
			{
				if (this._tblAdmin.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_adminIDChanging(value);
				this.SendPropertyChanging();
				this._fk_adminID = value;
				this.SendPropertyChanged("fk_adminID");
				this.Onfk_adminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vakkenID", DbType="Int NOT NULL")]
	public int fk_vakkenID
	{
		get
		{
			return this._fk_vakkenID;
		}
		set
		{
			if ((this._fk_vakkenID != value))
			{
				if (this._tblVakken.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakkenIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vakkenID = value;
				this.SendPropertyChanged("fk_vakkenID");
				this.Onfk_vakkenIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_rapportID", DbType="Int NOT NULL")]
	public int fk_rapportID
	{
		get
		{
			return this._fk_rapportID;
		}
		set
		{
			if ((this._fk_rapportID != value))
			{
				if (this._tblRapport.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_rapportIDChanging(value);
				this.SendPropertyChanging();
				this._fk_rapportID = value;
				this.SendPropertyChanged("fk_rapportID");
				this.Onfk_rapportIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAdmin_tblKoppel", Storage="_tblAdmin", ThisKey="fk_adminID", OtherKey="pk_adminID", IsForeignKey=true)]
	public tblAdmin tblAdmin
	{
		get
		{
			return this._tblAdmin.Entity;
		}
		set
		{
			tblAdmin previousValue = this._tblAdmin.Entity;
			if (((previousValue != value) 
						|| (this._tblAdmin.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblAdmin.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblAdmin.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_adminID = value.pk_adminID;
				}
				else
				{
					this._fk_adminID = default(int);
				}
				this.SendPropertyChanged("tblAdmin");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLeerkracht_tblKoppel", Storage="_tblLeerkracht", ThisKey="fk_leerkrachtID", OtherKey="pk_leerkrachtID", IsForeignKey=true)]
	public tblLeerkracht tblLeerkracht
	{
		get
		{
			return this._tblLeerkracht.Entity;
		}
		set
		{
			tblLeerkracht previousValue = this._tblLeerkracht.Entity;
			if (((previousValue != value) 
						|| (this._tblLeerkracht.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblLeerkracht.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblLeerkracht.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_leerkrachtID = value.pk_leerkrachtID;
				}
				else
				{
					this._fk_leerkrachtID = default(int);
				}
				this.SendPropertyChanged("tblLeerkracht");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRapport_tblKoppel", Storage="_tblRapport", ThisKey="fk_rapportID", OtherKey="pk_rapportID", IsForeignKey=true)]
	public tblRapport tblRapport
	{
		get
		{
			return this._tblRapport.Entity;
		}
		set
		{
			tblRapport previousValue = this._tblRapport.Entity;
			if (((previousValue != value) 
						|| (this._tblRapport.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblRapport.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblRapport.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_rapportID = value.pk_rapportID;
				}
				else
				{
					this._fk_rapportID = default(int);
				}
				this.SendPropertyChanged("tblRapport");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblKoppel", Storage="_tblStudent", ThisKey="fk_leerlingID", OtherKey="pk_leerlingID", IsForeignKey=true)]
	public tblStudent tblStudent
	{
		get
		{
			return this._tblStudent.Entity;
		}
		set
		{
			tblStudent previousValue = this._tblStudent.Entity;
			if (((previousValue != value) 
						|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblStudent.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblStudent.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_leerlingID = value.pk_leerlingID;
				}
				else
				{
					this._fk_leerlingID = default(int);
				}
				this.SendPropertyChanged("tblStudent");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVakken_tblKoppel", Storage="_tblVakken", ThisKey="fk_vakkenID", OtherKey="pk_vakkenID", IsForeignKey=true)]
	public tblVakken tblVakken
	{
		get
		{
			return this._tblVakken.Entity;
		}
		set
		{
			tblVakken previousValue = this._tblVakken.Entity;
			if (((previousValue != value) 
						|| (this._tblVakken.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVakken.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblVakken.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_vakkenID = value.pk_vakkenID;
				}
				else
				{
					this._fk_vakkenID = default(int);
				}
				this.SendPropertyChanged("tblVakken");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVrijstelling_tblKoppel", Storage="_tblVrijstelling", ThisKey="fk_vrijstellingID", OtherKey="pk_vrijstellingID", IsForeignKey=true)]
	public tblVrijstelling tblVrijstelling
	{
		get
		{
			return this._tblVrijstelling.Entity;
		}
		set
		{
			tblVrijstelling previousValue = this._tblVrijstelling.Entity;
			if (((previousValue != value) 
						|| (this._tblVrijstelling.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVrijstelling.Entity = null;
					previousValue.tblKoppels.Remove(this);
				}
				this._tblVrijstelling.Entity = value;
				if ((value != null))
				{
					value.tblKoppels.Add(this);
					this._fk_vrijstellingID = value.pk_vrijstellingID;
				}
				else
				{
					this._fk_vrijstellingID = default(int);
				}
				this.SendPropertyChanged("tblVrijstelling");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
=======
	public System.Data.Linq.Table<Opleiding> Opleidings
	{
		get
		{
			return this.GetTable<Opleiding>();
		}
	}
	
	public System.Data.Linq.Table<Vrijstelling> Vrijstellings
	{
		get
		{
			return this.GetTable<Vrijstelling>();
		}
	}
	
	public System.Data.Linq.Table<Student> Students
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
	
	public System.Data.Linq.Table<Upload> Uploads
	{
		get
		{
			return this.GetTable<Upload>();
		}
	}
	
	public System.Data.Linq.Table<Vakken> Vakkens
	{
		get
		{
			return this.GetTable<Vakken>();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
		}
	}
}

<<<<<<< HEAD
[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLeerkracht")]
public partial class tblLeerkracht : INotifyPropertyChanging, INotifyPropertyChanged
=======
[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpleiding")]
public partial class Opleiding : INotifyPropertyChanging, INotifyPropertyChanged
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
<<<<<<< HEAD
	private int _pk_leerkrachtID;
	
	private string _leerkrachtNaam;
	
	private string _leerkrachtPW;
	
	private EntitySet<tblKoppel> _tblKoppels;
=======
	private int _pk_opleidingID;
	
	private string _opleidingNaam;
	
	private EntitySet<Student> _Students;
	
	private EntitySet<Vakken> _tblVakkens;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
<<<<<<< HEAD
    partial void Onpk_leerkrachtIDChanging(int value);
    partial void Onpk_leerkrachtIDChanged();
    partial void OnleerkrachtNaamChanging(string value);
    partial void OnleerkrachtNaamChanged();
    partial void OnleerkrachtPWChanging(string value);
    partial void OnleerkrachtPWChanged();
    #endregion
	
	public tblLeerkracht()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_leerkrachtID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_leerkrachtID
	{
		get
		{
			return this._pk_leerkrachtID;
		}
		set
		{
			if ((this._pk_leerkrachtID != value))
			{
				this.Onpk_leerkrachtIDChanging(value);
				this.SendPropertyChanging();
				this._pk_leerkrachtID = value;
				this.SendPropertyChanged("pk_leerkrachtID");
				this.Onpk_leerkrachtIDChanged();
=======
    partial void Onpk_opleidingIDChanging(int value);
    partial void Onpk_opleidingIDChanged();
    partial void OnopleidingNaamChanging(string value);
    partial void OnopleidingNaamChanged();
    #endregion
	
	public Opleiding()
	{
		this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
		this._tblVakkens = new EntitySet<Vakken>(new Action<Vakken>(this.attach_tblVakkens), new Action<Vakken>(this.detach_tblVakkens));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_opleidingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_opleidingID
	{
		get
		{
			return this._pk_opleidingID;
		}
		set
		{
			if ((this._pk_opleidingID != value))
			{
				this.Onpk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_opleidingID = value;
				this.SendPropertyChanged("pk_opleidingID");
				this.Onpk_opleidingIDChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leerkrachtNaam", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string leerkrachtNaam
	{
		get
		{
			return this._leerkrachtNaam;
		}
		set
		{
			if ((this._leerkrachtNaam != value))
			{
				this.OnleerkrachtNaamChanging(value);
				this.SendPropertyChanging();
				this._leerkrachtNaam = value;
				this.SendPropertyChanged("leerkrachtNaam");
				this.OnleerkrachtNaamChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opleidingNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string opleidingNaam
	{
		get
		{
			return this._opleidingNaam;
		}
		set
		{
			if ((this._opleidingNaam != value))
			{
				this.OnopleidingNaamChanging(value);
				this.SendPropertyChanging();
				this._opleidingNaam = value;
				this.SendPropertyChanged("opleidingNaam");
				this.OnopleidingNaamChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leerkrachtPW", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string leerkrachtPW
	{
		get
		{
			return this._leerkrachtPW;
		}
		set
		{
			if ((this._leerkrachtPW != value))
			{
				this.OnleerkrachtPWChanging(value);
				this.SendPropertyChanging();
				this._leerkrachtPW = value;
				this.SendPropertyChanged("leerkrachtPW");
				this.OnleerkrachtPWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLeerkracht_tblKoppel", Storage="_tblKoppels", ThisKey="pk_leerkrachtID", OtherKey="fk_leerkrachtID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
=======
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_Student", Storage="_Students", ThisKey="pk_opleidingID", OtherKey="fk_opleiding")]
	public EntitySet<Student> Students
	{
		get
		{
			return this._Students;
		}
		set
		{
			this._Students.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblVakken", Storage="_tblVakkens", ThisKey="pk_opleidingID", OtherKey="fk_opleidingID")]
	public EntitySet<Vakken> Vakkens
	{
		get
		{
			return this._tblVakkens;
		}
		set
		{
			this._tblVakkens.Assign(value);
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
<<<<<<< HEAD
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblLeerkracht = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblLeerkracht = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRapport")]
public partial class tblRapport : INotifyPropertyChanging, INotifyPropertyChanged
=======
	private void attach_Students(Student entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = this;
	}
	
	private void detach_Students(Student entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding = null;
	}
	
	private void attach_tblVakkens(Vakken entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding1 = this;
	}
	
	private void detach_tblVakkens(Vakken entity)
	{
		this.SendPropertyChanging();
		entity.Opleiding1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVrijstelling")]
public partial class Vrijstelling : INotifyPropertyChanging, INotifyPropertyChanged
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
<<<<<<< HEAD
	private int _pk_rapportID;
	
	private string _rapportNaam;
	
	private System.DateTime _rapportJaar;
	
	private string _rapportOpleiding;
	
	private string _rapportSchooladres;
	
	private string _rapportURL;
	
	private double _rapportStatus;
	
	private EntitySet<tblKoppel> _tblKoppels;
=======
	private int _pk_VrijstellingID;
	
	private int _fk_vak;
	
	private string _vak_extern;
	
	private string _school;
	
	private string _studiepunten;
	
	private EntitySet<Upload> _tblUploads;
	
	private EntityRef<Vakken> _tblVakken;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
<<<<<<< HEAD
    partial void Onpk_rapportIDChanging(int value);
    partial void Onpk_rapportIDChanged();
    partial void OnrapportNaamChanging(string value);
    partial void OnrapportNaamChanged();
    partial void OnrapportJaarChanging(System.DateTime value);
    partial void OnrapportJaarChanged();
    partial void OnrapportOpleidingChanging(string value);
    partial void OnrapportOpleidingChanged();
    partial void OnrapportSchooladresChanging(string value);
    partial void OnrapportSchooladresChanged();
    partial void OnrapportURLChanging(string value);
    partial void OnrapportURLChanged();
    partial void OnrapportStatusChanging(double value);
    partial void OnrapportStatusChanged();
    #endregion
	
	public tblRapport()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_rapportID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_rapportID
	{
		get
		{
			return this._pk_rapportID;
		}
		set
		{
			if ((this._pk_rapportID != value))
			{
				this.Onpk_rapportIDChanging(value);
				this.SendPropertyChanging();
				this._pk_rapportID = value;
				this.SendPropertyChanged("pk_rapportID");
				this.Onpk_rapportIDChanged();
=======
    partial void Onpk_VrijstellingIDChanging(int value);
    partial void Onpk_VrijstellingIDChanged();
    partial void Onfk_vakChanging(int value);
    partial void Onfk_vakChanged();
    partial void Onvak_externChanging(string value);
    partial void Onvak_externChanged();
    partial void OnschoolChanging(string value);
    partial void OnschoolChanged();
    partial void OnstudiepuntenChanging(string value);
    partial void OnstudiepuntenChanged();
    #endregion
	
	public Vrijstelling()
	{
		this._tblUploads = new EntitySet<Upload>(new Action<Upload>(this.attach_tblUploads), new Action<Upload>(this.detach_tblUploads));
		this._tblVakken = default(EntityRef<Vakken>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_VrijstellingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_VrijstellingID
	{
		get
		{
			return this._pk_VrijstellingID;
		}
		set
		{
			if ((this._pk_VrijstellingID != value))
			{
				this.Onpk_VrijstellingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_VrijstellingID = value;
				this.SendPropertyChanged("pk_VrijstellingID");
				this.Onpk_VrijstellingIDChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rapportNaam
	{
		get
		{
			return this._rapportNaam;
		}
		set
		{
			if ((this._rapportNaam != value))
			{
				this.OnrapportNaamChanging(value);
				this.SendPropertyChanging();
				this._rapportNaam = value;
				this.SendPropertyChanged("rapportNaam");
				this.OnrapportNaamChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vak", DbType="Int NOT NULL")]
	public int fk_vak
	{
		get
		{
			return this._fk_vak;
		}
		set
		{
			if ((this._fk_vak != value))
			{
				if (this._tblVakken.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vakChanging(value);
				this.SendPropertyChanging();
				this._fk_vak = value;
				this.SendPropertyChanged("fk_vak");
				this.Onfk_vakChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportJaar", DbType="DateTime NOT NULL")]
	public System.DateTime rapportJaar
	{
		get
		{
			return this._rapportJaar;
		}
		set
		{
			if ((this._rapportJaar != value))
			{
				this.OnrapportJaarChanging(value);
				this.SendPropertyChanging();
				this._rapportJaar = value;
				this.SendPropertyChanged("rapportJaar");
				this.OnrapportJaarChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vak_extern", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vak_extern
	{
		get
		{
			return this._vak_extern;
		}
		set
		{
			if ((this._vak_extern != value))
			{
				this.Onvak_externChanging(value);
				this.SendPropertyChanging();
				this._vak_extern = value;
				this.SendPropertyChanged("vak_extern");
				this.Onvak_externChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportOpleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rapportOpleiding
	{
		get
		{
			return this._rapportOpleiding;
		}
		set
		{
			if ((this._rapportOpleiding != value))
			{
				this.OnrapportOpleidingChanging(value);
				this.SendPropertyChanging();
				this._rapportOpleiding = value;
				this.SendPropertyChanged("rapportOpleiding");
				this.OnrapportOpleidingChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string school
	{
		get
		{
			return this._school;
		}
		set
		{
			if ((this._school != value))
			{
				this.OnschoolChanging(value);
				this.SendPropertyChanging();
				this._school = value;
				this.SendPropertyChanged("school");
				this.OnschoolChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportSchooladres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rapportSchooladres
	{
		get
		{
			return this._rapportSchooladres;
		}
		set
		{
			if ((this._rapportSchooladres != value))
			{
				this.OnrapportSchooladresChanging(value);
				this.SendPropertyChanging();
				this._rapportSchooladres = value;
				this.SendPropertyChanged("rapportSchooladres");
				this.OnrapportSchooladresChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studiepunten", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studiepunten
	{
		get
		{
			return this._studiepunten;
		}
		set
		{
			if ((this._studiepunten != value))
			{
				this.OnstudiepuntenChanging(value);
				this.SendPropertyChanging();
				this._studiepunten = value;
				this.SendPropertyChanged("studiepunten");
				this.OnstudiepuntenChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportURL", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string rapportURL
	{
		get
		{
			return this._rapportURL;
		}
		set
		{
			if ((this._rapportURL != value))
			{
				this.OnrapportURLChanging(value);
				this.SendPropertyChanging();
				this._rapportURL = value;
				this.SendPropertyChanged("rapportURL");
				this.OnrapportURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rapportStatus", DbType="Float NOT NULL")]
	public double rapportStatus
	{
		get
		{
			return this._rapportStatus;
		}
		set
		{
			if ((this._rapportStatus != value))
			{
				this.OnrapportStatusChanging(value);
				this.SendPropertyChanging();
				this._rapportStatus = value;
				this.SendPropertyChanged("rapportStatus");
				this.OnrapportStatusChanged();
=======
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVrijstelling_tblUpload", Storage="_tblUploads", ThisKey="pk_VrijstellingID", OtherKey="fk_vrijstellingID")]
	public EntitySet<Upload> Uploads
	{
		get
		{
			return this._tblUploads;
		}
		set
		{
			this._tblUploads.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVakken_tblVrijstelling", Storage="_tblVakken", ThisKey="fk_vak", OtherKey="pk_vak", IsForeignKey=true)]
	public Vakken Vakken
	{
		get
		{
			return this._tblVakken.Entity;
		}
		set
		{
			Vakken previousValue = this._tblVakken.Entity;
			if (((previousValue != value) 
						|| (this._tblVakken.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVakken.Entity = null;
					previousValue.Vrijstellings.Remove(this);
				}
				this._tblVakken.Entity = value;
				if ((value != null))
				{
					value.Vrijstellings.Add(this);
					this._fk_vak = value.pk_vak;
				}
				else
				{
					this._fk_vak = default(int);
				}
				this.SendPropertyChanged("Vakken");
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRapport_tblKoppel", Storage="_tblKoppels", ThisKey="pk_rapportID", OtherKey="fk_rapportID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
		}
	}
	
=======
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
<<<<<<< HEAD
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblRapport = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblRapport = null;
=======
	private void attach_tblUploads(Upload entity)
	{
		this.SendPropertyChanging();
		entity.Vrijstelling = this;
	}
	
	private void detach_tblUploads(Upload entity)
	{
		this.SendPropertyChanging();
		entity.Vrijstelling = null;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
<<<<<<< HEAD
public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
=======
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
<<<<<<< HEAD
	private int _pk_leerlingID;
	
	private string _studentVoornaam;
	
	private string _studentNaam;
	
	private string _studentPasswd;
	
	private int _StudentNr;
	
	private string _StudentOpleiding;
	
	private EntitySet<tblKoppel> _tblKoppels;
=======
	private int _pk_student;
	
	private int _fk_opleiding;
	
	private string _studentNr;
	
	private string _studentNaam;
	
	private string _studentVoornaam;
	
	private string _studentWachtwoord;
	
	private EntityRef<Opleiding> _tblOpleiding;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
<<<<<<< HEAD
    partial void Onpk_leerlingIDChanging(int value);
    partial void Onpk_leerlingIDChanged();
    partial void OnstudentVoornaamChanging(string value);
    partial void OnstudentVoornaamChanged();
    partial void OnstudentNaamChanging(string value);
    partial void OnstudentNaamChanged();
    partial void OnstudentPasswdChanging(string value);
    partial void OnstudentPasswdChanged();
    partial void OnStudentNrChanging(int value);
    partial void OnStudentNrChanged();
    partial void OnStudentOpleidingChanging(string value);
    partial void OnStudentOpleidingChanged();
    #endregion
	
	public tblStudent()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_leerlingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_leerlingID
	{
		get
		{
			return this._pk_leerlingID;
		}
		set
		{
			if ((this._pk_leerlingID != value))
			{
				this.Onpk_leerlingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_leerlingID = value;
				this.SendPropertyChanged("pk_leerlingID");
				this.Onpk_leerlingIDChanged();
=======
    partial void Onpk_studentChanging(int value);
    partial void Onpk_studentChanged();
    partial void Onfk_opleidingChanging(int value);
    partial void Onfk_opleidingChanged();
    partial void OnstudentNrChanging(string value);
    partial void OnstudentNrChanged();
    partial void OnstudentNaamChanging(string value);
    partial void OnstudentNaamChanged();
    partial void OnstudentVoornaamChanging(string value);
    partial void OnstudentVoornaamChanged();
    partial void OnstudentWachtwoordChanging(string value);
    partial void OnstudentWachtwoordChanged();
    #endregion
	
	public Student()
	{
		this._tblOpleiding = default(EntityRef<Opleiding>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_student", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_student
	{
		get
		{
			return this._pk_student;
		}
		set
		{
			if ((this._pk_student != value))
			{
				this.Onpk_studentChanging(value);
				this.SendPropertyChanging();
				this._pk_student = value;
				this.SendPropertyChanged("pk_student");
				this.Onpk_studentChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentVoornaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentVoornaam
	{
		get
		{
			return this._studentVoornaam;
		}
		set
		{
			if ((this._studentVoornaam != value))
			{
				this.OnstudentVoornaamChanging(value);
				this.SendPropertyChanging();
				this._studentVoornaam = value;
				this.SendPropertyChanged("studentVoornaam");
				this.OnstudentVoornaamChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleiding", DbType="Int NOT NULL")]
	public int fk_opleiding
	{
		get
		{
			return this._fk_opleiding;
		}
		set
		{
			if ((this._fk_opleiding != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingChanging(value);
				this.SendPropertyChanging();
				this._fk_opleiding = value;
				this.SendPropertyChanged("fk_opleiding");
				this.Onfk_opleidingChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNaam
	{
		get
		{
			return this._studentNaam;
		}
		set
		{
			if ((this._studentNaam != value))
			{
				this.OnstudentNaamChanging(value);
				this.SendPropertyChanging();
				this._studentNaam = value;
				this.SendPropertyChanged("studentNaam");
				this.OnstudentNaamChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNr", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNr
	{
		get
		{
			return this._studentNr;
		}
		set
		{
			if ((this._studentNr != value))
			{
				this.OnstudentNrChanging(value);
				this.SendPropertyChanging();
				this._studentNr = value;
				this.SendPropertyChanged("studentNr");
				this.OnstudentNrChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentPasswd", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentPasswd
	{
		get
		{
			return this._studentPasswd;
		}
		set
		{
			if ((this._studentPasswd != value))
			{
				this.OnstudentPasswdChanging(value);
				this.SendPropertyChanging();
				this._studentPasswd = value;
				this.SendPropertyChanged("studentPasswd");
				this.OnstudentPasswdChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentNaam
	{
		get
		{
			return this._studentNaam;
		}
		set
		{
			if ((this._studentNaam != value))
			{
				this.OnstudentNaamChanging(value);
				this.SendPropertyChanging();
				this._studentNaam = value;
				this.SendPropertyChanged("studentNaam");
				this.OnstudentNaamChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNr", DbType="Int NOT NULL")]
	public int StudentNr
	{
		get
		{
			return this._StudentNr;
		}
		set
		{
			if ((this._StudentNr != value))
			{
				this.OnStudentNrChanging(value);
				this.SendPropertyChanging();
				this._StudentNr = value;
				this.SendPropertyChanged("StudentNr");
				this.OnStudentNrChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentVoornaam", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string studentVoornaam
	{
		get
		{
			return this._studentVoornaam;
		}
		set
		{
			if ((this._studentVoornaam != value))
			{
				this.OnstudentVoornaamChanging(value);
				this.SendPropertyChanging();
				this._studentVoornaam = value;
				this.SendPropertyChanged("studentVoornaam");
				this.OnstudentVoornaamChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentOpleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string StudentOpleiding
	{
		get
		{
			return this._StudentOpleiding;
		}
		set
		{
			if ((this._StudentOpleiding != value))
			{
				this.OnStudentOpleidingChanging(value);
				this.SendPropertyChanging();
				this._StudentOpleiding = value;
				this.SendPropertyChanged("StudentOpleiding");
				this.OnStudentOpleidingChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentWachtwoord", DbType="NVarChar(MAX)")]
	public string studentWachtwoord
	{
		get
		{
			return this._studentWachtwoord;
		}
		set
		{
			if ((this._studentWachtwoord != value))
			{
				this.OnstudentWachtwoordChanging(value);
				this.SendPropertyChanging();
				this._studentWachtwoord = value;
				this.SendPropertyChanged("studentWachtwoord");
				this.OnstudentWachtwoordChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblKoppel", Storage="_tblKoppels", ThisKey="pk_leerlingID", OtherKey="fk_leerlingID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
=======
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_Student", Storage="_tblOpleiding", ThisKey="fk_opleiding", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public Opleiding Opleiding
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			Opleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.Students.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.Students.Add(this);
					this._fk_opleiding = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleiding = default(int);
				}
				this.SendPropertyChanged("Opleiding");
			}
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
<<<<<<< HEAD
	
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblStudent = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblStudent = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVakken")]
public partial class tblVakken : INotifyPropertyChanging, INotifyPropertyChanged
=======
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUpload")]
public partial class Upload : INotifyPropertyChanging, INotifyPropertyChanged
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
<<<<<<< HEAD
	private int _pk_vakkenID;
	
	private string _vakNaam;
	
	private int _vakStudiepunten;
	
	private string _vakOpleiding;
	
	private EntitySet<tblKoppel> _tblKoppels;
=======
	private int _UploadID;
	
	private int _fk_vrijstellingID;
	
	private string _titel;
	
	private double _type;
	
	private EntityRef<Vrijstelling> _tblVrijstelling;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
<<<<<<< HEAD
    partial void Onpk_vakkenIDChanging(int value);
    partial void Onpk_vakkenIDChanged();
    partial void OnvakNaamChanging(string value);
    partial void OnvakNaamChanged();
    partial void OnvakStudiepuntenChanging(int value);
    partial void OnvakStudiepuntenChanged();
    partial void OnvakOpleidingChanging(string value);
    partial void OnvakOpleidingChanged();
    #endregion
	
	public tblVakken()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vakkenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_vakkenID
	{
		get
		{
			return this._pk_vakkenID;
		}
		set
		{
			if ((this._pk_vakkenID != value))
			{
				this.Onpk_vakkenIDChanging(value);
				this.SendPropertyChanging();
				this._pk_vakkenID = value;
				this.SendPropertyChanged("pk_vakkenID");
				this.Onpk_vakkenIDChanged();
=======
    partial void OnUploadIDChanging(int value);
    partial void OnUploadIDChanged();
    partial void Onfk_vrijstellingIDChanging(int value);
    partial void Onfk_vrijstellingIDChanged();
    partial void OntitelChanging(string value);
    partial void OntitelChanged();
    partial void OntypeChanging(double value);
    partial void OntypeChanged();
    #endregion
	
	public Upload()
	{
		this._tblVrijstelling = default(EntityRef<Vrijstelling>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UploadID
	{
		get
		{
			return this._UploadID;
		}
		set
		{
			if ((this._UploadID != value))
			{
				this.OnUploadIDChanging(value);
				this.SendPropertyChanging();
				this._UploadID = value;
				this.SendPropertyChanged("UploadID");
				this.OnUploadIDChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakNaam", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vakNaam
	{
		get
		{
			return this._vakNaam;
		}
		set
		{
			if ((this._vakNaam != value))
			{
				this.OnvakNaamChanging(value);
				this.SendPropertyChanging();
				this._vakNaam = value;
				this.SendPropertyChanged("vakNaam");
				this.OnvakNaamChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_vrijstellingID", DbType="Int NOT NULL")]
	public int fk_vrijstellingID
	{
		get
		{
			return this._fk_vrijstellingID;
		}
		set
		{
			if ((this._fk_vrijstellingID != value))
			{
				if (this._tblVrijstelling.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_vrijstellingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_vrijstellingID = value;
				this.SendPropertyChanged("fk_vrijstellingID");
				this.Onfk_vrijstellingIDChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakStudiepunten", DbType="Int NOT NULL")]
	public int vakStudiepunten
	{
		get
		{
			return this._vakStudiepunten;
		}
		set
		{
			if ((this._vakStudiepunten != value))
			{
				this.OnvakStudiepuntenChanging(value);
				this.SendPropertyChanging();
				this._vakStudiepunten = value;
				this.SendPropertyChanged("vakStudiepunten");
				this.OnvakStudiepuntenChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titel", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string titel
	{
		get
		{
			return this._titel;
		}
		set
		{
			if ((this._titel != value))
			{
				this.OntitelChanging(value);
				this.SendPropertyChanging();
				this._titel = value;
				this.SendPropertyChanged("titel");
				this.OntitelChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vakOpleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vakOpleiding
	{
		get
		{
			return this._vakOpleiding;
		}
		set
		{
			if ((this._vakOpleiding != value))
			{
				this.OnvakOpleidingChanging(value);
				this.SendPropertyChanging();
				this._vakOpleiding = value;
				this.SendPropertyChanged("vakOpleiding");
				this.OnvakOpleidingChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Float NOT NULL")]
	public double type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVakken_tblKoppel", Storage="_tblKoppels", ThisKey="pk_vakkenID", OtherKey="fk_vakkenID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
=======
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVrijstelling_tblUpload", Storage="_tblVrijstelling", ThisKey="fk_vrijstellingID", OtherKey="pk_VrijstellingID", IsForeignKey=true)]
	public Vrijstelling Vrijstelling
	{
		get
		{
			return this._tblVrijstelling.Entity;
		}
		set
		{
			Vrijstelling previousValue = this._tblVrijstelling.Entity;
			if (((previousValue != value) 
						|| (this._tblVrijstelling.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblVrijstelling.Entity = null;
					previousValue.Uploads.Remove(this);
				}
				this._tblVrijstelling.Entity = value;
				if ((value != null))
				{
					value.Uploads.Add(this);
					this._fk_vrijstellingID = value.pk_VrijstellingID;
				}
				else
				{
					this._fk_vrijstellingID = default(int);
				}
				this.SendPropertyChanged("Vrijstelling");
			}
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
<<<<<<< HEAD
	
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblVakken = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblVakken = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVrijstelling")]
public partial class tblVrijstelling : INotifyPropertyChanging, INotifyPropertyChanged
=======
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVakken")]
public partial class Vakken : INotifyPropertyChanging, INotifyPropertyChanged
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
<<<<<<< HEAD
	private int _pk_vrijstellingID;
	
	private string _vrijstellingStudiemateriaal;
	
	private int _vrijstellingSchooljaar;
	
	private string _vrijstellingOpleidinggev;
	
	private string _vrijstellingSchoolgeg;
	
	private string _vrijstellingVak;
	
	private int _vrijstellingVakSP;
	
	private EntitySet<tblKoppel> _tblKoppels;
=======
	private int _pk_vak;
	
	private string _opleiding;
	
	private int _fk_opleidingID;
	
	private EntitySet<Vrijstelling> _tblVrijstellings;
	
	private EntityRef<Opleiding> _tblOpleiding;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
<<<<<<< HEAD
    partial void Onpk_vrijstellingIDChanging(int value);
    partial void Onpk_vrijstellingIDChanged();
    partial void OnvrijstellingStudiemateriaalChanging(string value);
    partial void OnvrijstellingStudiemateriaalChanged();
    partial void OnvrijstellingSchooljaarChanging(int value);
    partial void OnvrijstellingSchooljaarChanged();
    partial void OnvrijstellingOpleidinggevChanging(string value);
    partial void OnvrijstellingOpleidinggevChanged();
    partial void OnvrijstellingSchoolgegChanging(string value);
    partial void OnvrijstellingSchoolgegChanged();
    partial void OnvrijstellingVakChanging(string value);
    partial void OnvrijstellingVakChanged();
    partial void OnvrijstellingVakSPChanging(int value);
    partial void OnvrijstellingVakSPChanged();
    #endregion
	
	public tblVrijstelling()
	{
		this._tblKoppels = new EntitySet<tblKoppel>(new Action<tblKoppel>(this.attach_tblKoppels), new Action<tblKoppel>(this.detach_tblKoppels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vrijstellingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_vrijstellingID
	{
		get
		{
			return this._pk_vrijstellingID;
		}
		set
		{
			if ((this._pk_vrijstellingID != value))
			{
				this.Onpk_vrijstellingIDChanging(value);
				this.SendPropertyChanging();
				this._pk_vrijstellingID = value;
				this.SendPropertyChanged("pk_vrijstellingID");
				this.Onpk_vrijstellingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingStudiemateriaal", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vrijstellingStudiemateriaal
	{
		get
		{
			return this._vrijstellingStudiemateriaal;
		}
		set
		{
			if ((this._vrijstellingStudiemateriaal != value))
			{
				this.OnvrijstellingStudiemateriaalChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingStudiemateriaal = value;
				this.SendPropertyChanged("vrijstellingStudiemateriaal");
				this.OnvrijstellingStudiemateriaalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingSchooljaar", DbType="Int NOT NULL")]
	public int vrijstellingSchooljaar
	{
		get
		{
			return this._vrijstellingSchooljaar;
		}
		set
		{
			if ((this._vrijstellingSchooljaar != value))
			{
				this.OnvrijstellingSchooljaarChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingSchooljaar = value;
				this.SendPropertyChanged("vrijstellingSchooljaar");
				this.OnvrijstellingSchooljaarChanged();
=======
    partial void Onpk_vakChanging(int value);
    partial void Onpk_vakChanged();
    partial void OnopleidingChanging(string value);
    partial void OnopleidingChanged();
    partial void Onfk_opleidingIDChanging(int value);
    partial void Onfk_opleidingIDChanged();
    #endregion
	
	public Vakken()
	{
		this._tblVrijstellings = new EntitySet<Vrijstelling>(new Action<Vrijstelling>(this.attach_tblVrijstellings), new Action<Vrijstelling>(this.detach_tblVrijstellings));
		this._tblOpleiding = default(EntityRef<Opleiding>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_vak", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pk_vak
	{
		get
		{
			return this._pk_vak;
		}
		set
		{
			if ((this._pk_vak != value))
			{
				this.Onpk_vakChanging(value);
				this.SendPropertyChanging();
				this._pk_vak = value;
				this.SendPropertyChanged("pk_vak");
				this.Onpk_vakChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingOpleidinggev", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vrijstellingOpleidinggev
	{
		get
		{
			return this._vrijstellingOpleidinggev;
		}
		set
		{
			if ((this._vrijstellingOpleidinggev != value))
			{
				this.OnvrijstellingOpleidinggevChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingOpleidinggev = value;
				this.SendPropertyChanged("vrijstellingOpleidinggev");
				this.OnvrijstellingOpleidinggevChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opleiding", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string opleiding
	{
		get
		{
			return this._opleiding;
		}
		set
		{
			if ((this._opleiding != value))
			{
				this.OnopleidingChanging(value);
				this.SendPropertyChanging();
				this._opleiding = value;
				this.SendPropertyChanged("opleiding");
				this.OnopleidingChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingSchoolgeg", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vrijstellingSchoolgeg
	{
		get
		{
			return this._vrijstellingSchoolgeg;
		}
		set
		{
			if ((this._vrijstellingSchoolgeg != value))
			{
				this.OnvrijstellingSchoolgegChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingSchoolgeg = value;
				this.SendPropertyChanged("vrijstellingSchoolgeg");
				this.OnvrijstellingSchoolgegChanged();
=======
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_opleidingID", DbType="Int NOT NULL")]
	public int fk_opleidingID
	{
		get
		{
			return this._fk_opleidingID;
		}
		set
		{
			if ((this._fk_opleidingID != value))
			{
				if (this._tblOpleiding.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onfk_opleidingIDChanging(value);
				this.SendPropertyChanging();
				this._fk_opleidingID = value;
				this.SendPropertyChanged("fk_opleidingID");
				this.Onfk_opleidingIDChanged();
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingVak", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string vrijstellingVak
	{
		get
		{
			return this._vrijstellingVak;
		}
		set
		{
			if ((this._vrijstellingVak != value))
			{
				this.OnvrijstellingVakChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingVak = value;
				this.SendPropertyChanged("vrijstellingVak");
				this.OnvrijstellingVakChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijstellingVakSP", DbType="Int NOT NULL")]
	public int vrijstellingVakSP
	{
		get
		{
			return this._vrijstellingVakSP;
		}
		set
		{
			if ((this._vrijstellingVakSP != value))
			{
				this.OnvrijstellingVakSPChanging(value);
				this.SendPropertyChanging();
				this._vrijstellingVakSP = value;
				this.SendPropertyChanged("vrijstellingVakSP");
				this.OnvrijstellingVakSPChanged();
=======
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVakken_tblVrijstelling", Storage="_tblVrijstellings", ThisKey="pk_vak", OtherKey="fk_vak")]
	public EntitySet<Vrijstelling> Vrijstellings
	{
		get
		{
			return this._tblVrijstellings;
		}
		set
		{
			this._tblVrijstellings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblOpleiding_tblVakken", Storage="_tblOpleiding", ThisKey="fk_opleidingID", OtherKey="pk_opleidingID", IsForeignKey=true)]
	public Opleiding Opleiding1
	{
		get
		{
			return this._tblOpleiding.Entity;
		}
		set
		{
			Opleiding previousValue = this._tblOpleiding.Entity;
			if (((previousValue != value) 
						|| (this._tblOpleiding.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblOpleiding.Entity = null;
					previousValue.Vakkens.Remove(this);
				}
				this._tblOpleiding.Entity = value;
				if ((value != null))
				{
					value.Vakkens.Add(this);
					this._fk_opleidingID = value.pk_opleidingID;
				}
				else
				{
					this._fk_opleidingID = default(int);
				}
				this.SendPropertyChanged("Opleiding1");
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
			}
		}
	}
	
<<<<<<< HEAD
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVrijstelling_tblKoppel", Storage="_tblKoppels", ThisKey="pk_vrijstellingID", OtherKey="fk_vrijstellingID")]
	public EntitySet<tblKoppel> tblKoppels
	{
		get
		{
			return this._tblKoppels;
		}
		set
		{
			this._tblKoppels.Assign(value);
		}
	}
	
=======
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
<<<<<<< HEAD
	private void attach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblVrijstelling = this;
	}
	
	private void detach_tblKoppels(tblKoppel entity)
	{
		this.SendPropertyChanging();
		entity.tblVrijstelling = null;
=======
	private void attach_tblVrijstellings(Vrijstelling entity)
	{
		this.SendPropertyChanging();
		entity.Vakken = this;
	}
	
	private void detach_tblVrijstellings(Vrijstelling entity)
	{
		this.SendPropertyChanging();
		entity.Vakken = null;
>>>>>>> c8cd77824cee482116885fb171b2184db1a2eb80
	}
}
#pragma warning restore 1591
