<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="VrijstellingenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblOpleiding" Member="Opleidings">
    <Type Name="Opleiding">
      <Column Name="pk_opleidingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="opleidingNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblOpleiding_Student" Member="Students" ThisKey="pk_opleidingID" OtherKey="fk_opleiding" Type="Student" />
      <Association Name="tblOpleiding_tblVakken" Member="Vakkens" Storage="_tblVakkens" ThisKey="pk_opleidingID" OtherKey="fk_opleidingID" Type="Vakken" />
    </Type>
  </Table>
  <Table Name="dbo.tblVrijstelling" Member="Vrijstellings">
    <Type Name="Vrijstelling">
      <Column Name="pk_VrijstellingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_vak" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vak_extern" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="school" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studiepunten" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblVrijstelling_tblUpload" Member="Uploads" Storage="_tblUploads" ThisKey="pk_VrijstellingID" OtherKey="fk_vrijstellingID" Type="Upload" />
      <Association Name="tblVakken_tblVrijstelling" Member="Vakken" Storage="_tblVakken" ThisKey="fk_vak" OtherKey="pk_vak" Type="Vakken" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudent" Member="Students">
    <Type Name="Student">
      <Column Name="pk_student" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_opleiding" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentNr" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentVoornaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentWachtwoord" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tblOpleiding_Student" Member="Opleiding" Storage="_tblOpleiding" ThisKey="fk_opleiding" OtherKey="pk_opleidingID" Type="Opleiding" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUpload" Member="Uploads">
    <Type Name="Upload">
      <Column Name="UploadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_vrijstellingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="titel" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tblVrijstelling_tblUpload" Member="Vrijstelling" Storage="_tblVrijstelling" ThisKey="fk_vrijstellingID" OtherKey="pk_VrijstellingID" Type="Vrijstelling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblVakken" Member="Vakkens">
    <Type Name="Vakken">
      <Column Name="pk_vak" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="opleiding" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_opleidingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblVakken_tblVrijstelling" Member="Vrijstellings" Storage="_tblVrijstellings" ThisKey="pk_vak" OtherKey="fk_vak" Type="Vrijstelling" />
      <Association Name="tblOpleiding_tblVakken" Member="Opleiding1" Storage="_tblOpleiding" ThisKey="fk_opleidingID" OtherKey="pk_opleidingID" Type="Opleiding" IsForeignKey="true" />
    </Type>
  </Table>
</Database>