<?xml version="1.0" encoding="utf-8"?><Database Name="DBvrijstellingen" Class="VrijstellingenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\DBvrijstellingen.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBvrijstellingenConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAdmin" Member="tblAdmins">
    <Type Name="tblAdmin">
      <Column Name="pk_adminID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="adminStatus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="adminBijlage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="adminGoedgekeurd" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fk_caseID" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="tblAdmin_tblKoppel" Member="tblKoppels" ThisKey="pk_adminID" OtherKey="fk_adminID" Type="tblKoppel" />
    </Type>
  </Table>
  <Table Name="dbo.tblKoppel" Member="tblKoppels">
    <Type Name="tblKoppel">
      <Column Name="pk_caseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_leerlingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_vrijstellingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_leerkrachtID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_adminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_vakkenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_rapportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblAdmin_tblKoppel" Member="tblAdmin" ThisKey="fk_adminID" OtherKey="pk_adminID" Type="tblAdmin" IsForeignKey="true" />
      <Association Name="tblLeerkracht_tblKoppel" Member="tblLeerkracht" ThisKey="fk_leerkrachtID" OtherKey="pk_leerkrachtID" Type="tblLeerkracht" IsForeignKey="true" />
      <Association Name="tblRapport_tblKoppel" Member="tblRapport" ThisKey="fk_rapportID" OtherKey="pk_rapportID" Type="tblRapport" IsForeignKey="true" />
      <Association Name="tblStudent_tblKoppel" Member="tblStudent" ThisKey="fk_leerlingID" OtherKey="pk_leerlingID" Type="tblStudent" IsForeignKey="true" />
      <Association Name="tblVakken_tblKoppel" Member="tblVakken" ThisKey="fk_vakkenID" OtherKey="pk_vakkenID" Type="tblVakken" IsForeignKey="true" />
      <Association Name="tblVrijstelling_tblKoppel" Member="tblVrijstelling" ThisKey="fk_vrijstellingID" OtherKey="pk_vrijstellingID" Type="tblVrijstelling" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLeerkracht" Member="tblLeerkrachts">
    <Type Name="tblLeerkracht">
      <Column Name="pk_leerkrachtID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="leerkrachtNaam" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="leerkrachtPW" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblLeerkracht_tblKoppel" Member="tblKoppels" ThisKey="pk_leerkrachtID" OtherKey="fk_leerkrachtID" Type="tblKoppel" />
    </Type>
  </Table>
  <Table Name="dbo.tblRapport" Member="tblRapports">
    <Type Name="tblRapport">
      <Column Name="pk_rapportID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rapportNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rapportJaar" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="rapportOpleiding" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rapportSchooladres" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rapportURL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rapportStatus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tblRapport_tblKoppel" Member="tblKoppels" ThisKey="pk_rapportID" OtherKey="fk_rapportID" Type="tblKoppel" />
    </Type>
  </Table>
  <Table Name="dbo.tblStudent" Member="tblStudents">
    <Type Name="tblStudent">
      <Column Name="pk_leerlingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="studentVoornaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentNaam" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="studentPasswd" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StudentNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentOpleiding" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblStudent_tblKoppel" Member="tblKoppels" ThisKey="pk_leerlingID" OtherKey="fk_leerlingID" Type="tblKoppel" />
    </Type>
  </Table>
  <Table Name="dbo.tblVakken" Member="tblVakkens">
    <Type Name="tblVakken">
      <Column Name="pk_vakkenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vakNaam" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vakStudiepunten" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vakOpleiding" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tblVakken_tblKoppel" Member="tblKoppels" ThisKey="pk_vakkenID" OtherKey="fk_vakkenID" Type="tblKoppel" />
    </Type>
  </Table>
  <Table Name="dbo.tblVrijstelling" Member="tblVrijstellings">
    <Type Name="tblVrijstelling">
      <Column Name="pk_vrijstellingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vrijstellingStudiemateriaal" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vrijstellingSchooljaar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vrijstellingOpleidinggev" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vrijstellingSchoolgeg" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vrijstellingVak" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="vrijstellingVakSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblVrijstelling_tblKoppel" Member="tblKoppels" ThisKey="pk_vrijstellingID" OtherKey="fk_vrijstellingID" Type="tblKoppel" />
    </Type>
  </Table>
</Database>